name: Deploy Backend (Runner)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Docker
        run: |
          cd /home/ubuntu/backend
          git pull origin main
          docker compose up -d --build
